### ISSUE TITLE
Submit raw transaction

### ISSUE THREAD

**Issue by axic** [ewasm/etherchain-light#11]
For any input it just says "Transaction submitted. Hash: 0x0000000000000000000000000000000000000000000000000000000000000000"

**Comment by axic** [comment]
This seemed to be working last week (with geth).

Maybe it is an aleth issue?

**Comment by jwasinger** [comment]
Probably.  I think aleth gives that response for pending transactions.

**Comment by axic** [comment]
Closing this now as it works with geth. Will open again if someone verifies that it breaks with aleth.
