### ISSUE TITLE
Nicer look at feel

### ISSUE THREAD

**Issue by axic** [ewasm/etherchain-light#15]
In order to achieve it change `yeti` to `paper` in `config.js`:

```
  this.bootstrapUrl = "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css";
```

**Comment by axic** [comment]
Also could add the following to `this.names`:
```
    "0xefadf166849f06eee4b44ddb78e4162580f436b1": "ewasm Faucet",
    "0x031159df845ade415202e6da299223cb640b9db0": "ewasm miner1"
```

Though it only shows up on the blocks page and not on the accounts page.

**Comment by cdetrio** [comment]
names were added in https://github.com/ewasm/etherchain-light/pull/36
