### ISSUE TITLE
Balances are displayed with scientific notation

### ISSUE THREAD

**Issue by axic** [ewasm/etherchain-light#54]
e.g. "1.3371337e-11 ETH"

It should be displayed in a nicer form.

**Comment by axic** [comment]
It currently uses this file: https://github.com/ewasm/etherchain-light/blob/ewasm/utils/ethformatter.js

Consider using web3's toWei/fromWei: https://web3js.readthedocs.io/en/1.0/web3-utils.html#fromwei

**Comment by cdetrio** [comment]
Fixed in https://github.com/ewasm/etherchain-light/pull/57
